-- No-op migration.
-- The `team` table was already created by a prior migration (`20260123080704_add_team_model`).
-- Keeping this file intentionally empty avoids duplicate CREATE TABLE failures in shadow databases.
